name: Run Tests

on: [push, pull_request, workflow_dispatch]


jobs:
  compile:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: |
          cd Projects/P3/src
          java -version
          javac *.java

  TestConsume:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2
      - name: Test Consume
        run: |
          cd Projects/P3
          java -version
          javac -cp "src/:tests/:tests/junit-4.10.jar" src/*.java tests/*.java
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestConsume
 
 TestAttack:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2
      - name: Test Attack
        run: |
          cd Projects/P3
          java -version
          javac -cp "src/:tests/:tests/junit-4.10.jar" src/*.java tests/*.java
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestAttack

          
  TestMapEatCookie:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v2
      - name: Test MapEatCookie
        run: |
          cd Projects/P3
          java -version
          javac -cp "src/:tests/:tests/junit-4.10.jar" src/*.java tests/*.java
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestMapEatCookie